name: TP1-zip

on:
  push:
    branches: [ master , dev ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Zip TP1
      run: |
        make LAIG_TP1_T2_G04.zip
    - name: Upload user manual
      uses: actions/upload-artifact@v2
      with:
        name: LAIG_TP1_T2_G04.zip
        path: LAIG_TP1_T2_G04.zip