name: User manual

on:
  push:
    branches: [ master , dev ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install latex and related packages
      run: |
        sudo apt update
        sudo apt install -y texlive latexmk curl
    - name: Install pandoc
      run: |
        sudo apt install pandoc
    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Build user manual
      run: |
        cd TP3
        pandoc user-manual.md -o user-manual.pdf
    - name: Upload user manual
      uses: actions/upload-artifact@v2
      with:
        name: user-manual.pdf
        path: TP3/user-manual.pdf